package com.robinlb99.legalserviceportalapi.core.domain.enums;

public enum TipoDocumento {
    // Documentos de Identificación Personal
    IDENTIFICACION_OFICIAL,
    CURP,
    COMPROBANTE_DOMICILIO,
    ACTA_NACIMIENTO,
    RFC,
    
    // Documentos Generales
    CONTRATOS,
    CORRESPONDENCIA,
    FOTOGRAFIAS_EVIDENCIA,
    VIDEOS_GRABACIONES,
    DECLARACIONES_TESTIGOS,
    DICTAMENES_PERICIALES,
    
    // Derecho Civil y Mercantil
    CONTRATO_ORIGINAL,
    PAGARES,
    LETRAS_CAMBIO,
    FACTURAS,
    COMPROBANTES_PAGO,
    NOTIFICACIONES_EXTRAJUDICIALES,
    CORREOS_ELECTRONICOS,
    REPORTES_MEDICOS,
    PRESUPUESTOS_REPARACION,
    FOTOGRAFIAS_DANIO,
    REPORTES_PERITOS,
    COMPROBANTES_GASTOS,
    
    // Derecho Familiar
    ACTA_MATRIMONIO,
    ACTAS_NACIMIENTO_HIJOS,
    INVENTARIO_BIENES,
    COMPROBANTES_INGRESOS,
    ACUERDOS_PRENUPCIALES,
    COMPROBANTES_GASTOS_MENOR,
    ESTADOS_CUENTA,
    RECIBOS_COLEGIATURAS,
    GASTOS_MEDICOS,
    
    // Derecho Laboral
    CONTRATO_TRABAJO,
    RECIBOS_NOMINA,
    CARTAS_DESPIDO,
    COMUNICACIONES_INTERNAS,
    HORARIOS_ASISTENCIA,
    EVALUACIONES_DESEMPENO,
    
    // Derecho Penal
    DENUNCIA_QUERELLA,
    DECLARACIONES_MINISTERIO_PUBLICO,
    FOTOGRAFIAS_LESIONES,
    REPORTES_MEDICOS_PENALES,
    
    // Derecho Inmobiliario
    ESCRITURAS_PUBLICAS,
    TITULOS_PROPIEDAD,
    CONTRATOS_ARRENDAMIENTO,
    COMPROBANTES_PAGO_RENTA,
    FOTOGRAFIAS_INMUEBLE,
    AVALUOS,
    
    // Derecho Mercantil
    ACTA_CONSTITUTIVA,
    PODERES_NOTARIALES,
    ESTADOS_FINANCIEROS,
    CONTRATOS_COMERCIALES,
    FACTURAS_COMERCIALES,
    ORDENES_COMPRA,
    CORRESPONDENCIA_COMERCIAL,
    
    // Documentos Financieros
    ESTADOS_CUENTA_BANCARIOS,
    DECLARACIONES_FISCALES,
    CONTRATOS_CREDITO,
    POLIZAS_SEGURO,
    COMPROBANTES_INGRESOS_FINANCIEROS
}
